version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '65432:65432'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
    env_file:
      - docker.env

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data: